### ISSUE TITLE
Non-admin users using the setdeck command

### ISSUE THREAD

**Issue by ddrahos** [RyderL/Wargame-RCON#2]
It would be useful to be able to disable using the setdeck command in chat.

Today I had some player who changed his deck to REDFOR while on BLUFOR and made other public players upset. I told him to stop, and had to kick when he refused. I don't mind the people using the RCON tool to have the ability but having random players do it is annoying and open for abuse when an admin isn't present.

It would be useful to disable the command from being run from the chat command or having an option to enable/disable the feature in the config.js.

**Comment by RyderL** [comment]
ok, ill add this setting later

**Comment by RyderL** [comment]
switch has been added, enjoy :D

**Comment by ddrahos** [comment]
It didn't work? I can still use the chat commands.

![Capture](https://user-images.githubusercontent.com/127693081/226006639-ed00f571-cb94-4fd4-b259-8509016a3cf7.PNG)

**Comment by RyderL** [comment]
lol, i forgot a symbol, u need to wait, i have some other codes being adjusted, i will push the code after i pass the test

**Comment by RyderL** [comment]
done, try again

**Comment by ddrahos** [comment]
Thanks but I think you broke more stuff doing this haha...

The change you made breaks the message reader and the setdeck command doesn't work when enableChatCommand value in config.js is set to true.

If it's easier you can revert the changes and I will run Wargame without the +chat_log_file option which will disable it anyways. Thanks for trying but don't waste too much time on me haha.

Edit: might have broken deck restrict too.

**Comment by RyderL** [comment]
i didn't look carefully, because i was mainly modifying another function, and it must be working now :D

**Comment by ddrahos** [comment]
I see you're doing commits right now, I'll test them in a moment.

A problem I was having was the broken level indicator for players and the chat commands were still not working.

Also I found out that when I clear my log files every week it breaks the rcon. So if you run a script to clear them you need to recreate them right away and not rely on the server to do so.
`
rm serverlog.txt
touch serverlog.txt
rm chat.log
touch chat.log`

**Comment by RyderL** [comment]
after you restart the wrd service, you need to restart rcon once

**Comment by ddrahos** [comment]
Was playing around with the tool today, having some games. Here's a few observations:

- enableChatCommand works great
- the PlayerLevel indicator no longer works, just indicates lv: 1
- As you mentioned the cached playerlist problems

**Comment by RyderL** [comment]
the reason the player level indicator doesn't work is because i wanted to do some testing, so i commented out line 1072, you can try again after i fix the cache :D
